import { AppConfig, AppLogic } from "./global.slint";
import {NavView} from "./nav-view.slint";
import {MainView} from "./main-view.slint";
import {LaunchView} from "./launch-view.slint";
import { Button, HorizontalBox } from "std-widgets.slint";

export { AppConfig, AppLogic}

export component AppWindow inherits Window {
    title: "Solltun ";
    icon: @image-url("./icons/rocket.svg");

    background: black;
    preferred-width: 700px;
    preferred-height: 500px;

    if(!AppConfig.is-rocket-launched):LaunchView {
        on_launch => {
            AppConfig.is_rocket_launched = !AppConfig.is_rocket_launched;
        }
    }

    if(AppConfig.is-rocket-launched):HorizontalLayout {
        alignment: space-between;

        nav := NavView { }

        main := MainView { }
    }
}
