import { AppConfig, AppLogic } from "./global.slint";
import {NavView} from "./nav-view.slint";
import {MainView} from "./main-view.slint";
import {LaunchView} from "./launch-view.slint";
import { Button, HorizontalBox } from "std-widgets.slint";

export { AppConfig, AppLogic}

export component AppWindow inherits Window {
    title: "Solltun ";
    icon: @image-url("./icons/rocket.svg");
    in-out property <int> counter: 0;
    in-out property <string> app-name;
    in-out property <string> db-name;
    in-out property <string> db-path;
    in-out property <bool> open-curtain: true;
    in-out property <bool> is-rocket-launched: false;
    in-out property <[string]> tables: [];

    callback request-increase-value;

    background: black;
    preferred-width: 800px;
    preferred-height: 600px;

    if(!root.is-rocket-launched):LaunchView {
        on-launch => {
            AppLogic.init_db();
        }
    }

    if(root.is-rocket-launched):HorizontalLayout {
        alignment: space-between;

        nav := NavView {
            open_curtain: root.open-curtain;
            db_name: root.db-name;
            tables: root.tables;
            on-landing => {
                root.is-rocket-launched = !root.is-rocket-launched;
            }
        }

        main := MainView {
            counter: root.counter;
            db_name: root.db-name;
            db_path: root.db-path;
            open_curtain: root.open-curtain;

            toggle-curtain => {
                root.open-curtain = !root.open-curtain;
            }
        }
    }
}
