export component MyButton inherits Rectangle {
    in-out property text <=> txt.text;
    callback clicked <=> touch.clicked;

    border-radius: root.height / 2;
    border-width: 1px;
    border-color: root.background.darker(25%);
    background: touch.pressed ? greenyellow : touch.has-hover ? gold : goldenrod;
    height: txt.preferred-height * 1.33;
    min-width: txt.preferred-width + 20px;

    txt := Text {
        x: (parent.width - self.width) / 2 + (touch.pressed ? 2px : 0);
        y: (parent.height - self.height) / 2 + (touch.pressed ? 1px : 0);
        color: #000;
        font-weight: 700;
    }

    touch := TouchArea { }
}
