import { Button, HorizontalBox } from "std-widgets.slint";
import { AppConfig } from "global.slint";

export component Header inherits Rectangle {
    property <bool> hover <=> ta.has-hover;

    callback toggle_curtain;

    preferred-width: 100%;
    preferred-height: 10px;

    HorizontalLayout {
        alignment: space-between;

        hamburger := Image {
            source: @image-url("icons/hamburger.svg");
            width: 35px;
            height: 35px;

            ta := TouchArea {
                mouse-cursor: pointer;
                clicked => {
                    root.toggle_curtain();
                }
            }

            states [
                hovered when ta.has-hover: {
                    source: @image-url("icons/hamburger-gold.svg");
                }
            ]
        }

        Text {
            text: AppConfig.app_name;
            color: cyan;
            width: 100%;
            font-size: 32px;
            font-weight: 700;
            font-family: "Ubuntu";
            horizontal-alignment: center;
        }
    }
}
