import { HorizontalBox, Button } from "std-widgets.slint";
import {MyButton} from "custom-button.slint";

export component LaunchView inherits HorizontalLayout {
    alignment: center;
    horizontal-stretch: 100%;
    width: 100%;
    height: 100%;

    callback on_launch;

    VerticalLayout {
        alignment: center;
        width: 100%;
        height: 100%;

        HorizontalBox {
            alignment: center;
            horizontal-stretch: 100%;
            width: 100%;

            Image {
                source: @image-url("icons/rocket.svg");
                width: 300px;
                height: 300px;
                img-touch := TouchArea {
                    mouse-cursor: pointer;
                    clicked => {
                        root.on_launch();
                    }
                }
            }
        }

        HorizontalBox {
            alignment: center;
            horizontal-stretch: 100%;
            width: 100%;

            btn := MyButton {
                text: "Launch Rocket!";
                width: 150px;
                height: 40px;
                horizontal-stretch: 100%;
                clicked => {
                    img-touch.clicked();
                }
            }
        }
    }
}
