import { VerticalBox, Button, Spinner, TabWidget, LineEdit, HorizontalBox } from "std-widgets.slint";
import { Header } from "header-view.slint";
import { AppConfig } from "global.slint";

export component MainView inherits Rectangle {
    in-out property <bool> is-spinning: false;
    in-out property <string> username: "Rasoul";

    callback increase-value;

    width: AppConfig.is_curtain_open ? 85% : 100%;
    background: #060E06;
    animate width {
        duration: 250ms;
        easing: ease-in;
    }

    VerticalBox {
        alignment: space-between;

        VerticalBox {
            alignment: start;
            height: 90%;

            Header { }

            Text {
                color: white;
                text: "Username";
            }

            LineEdit {
                text <=> root.username;
                width: 250px;
                height: 30px;
                x: 5px;
                font-size: 1.2rem;
                input-type: text;
                accessible-role: text;
                placeholder-text: "Enter text to be transformed";
                edited => {
                    root.is-spinning = true;
                }
            }

            Spinner {
                width: 50px;
                height: 50px;
                indeterminate: root.is-spinning;
            }
        }

        HorizontalBox {
            alignment: start;
            spacing: 10px;

            Text {
                text: "Database: ";
                font-size: 1.2rem;
                color: AppConfig.color_primary;
            }

            Text {
                text: AppConfig.db_name;
                font-size: 1.1rem;
                color: AppConfig.color_secondary;
            }

            if (AppConfig.db_path != ""): Text {
                text: "(Path: \{AppConfig.db_path})";
                color: coral;
            }
        }
    }
}
