import { VerticalBox, Button } from "std-widgets.slint";
import { Title } from "title-window.slint";

export component MainWindow inherits Rectangle {
    in-out property <int> counter;
    in-out property <string> app_name;
    in-out property <string> db_name;
    in-out property <bool> open_curtain;

    callback clicked;
    callback toggle-curtain;
    callback add-db;

    width: open_curtain ? 85% : 100%;
    background: #060D06;
    animate width {
        duration: 250ms;
        easing: ease-in;
    }

    VerticalBox {
        alignment: start;
        Title {
            app_name: root.app_name;
            toggle_curtain => {
                root.toggle_curtain();
            }
        }

        Text {
            text: "Counter: \{root.counter}";
            color: green;
        }

        Text {
            text: "DB name: \{root.db_name}";
            color: blueviolet;
        }

        Button {
            width: 200px;
            height: 50px;
            text: "Increase value";
            primary: true;
            clicked => {
                root.clicked();
            }
        }

        Button {
            width: 200px;
            height: 50px;
            text: "Add database";
            primary: true;
            clicked => {
                root.add-db();
            }
        }
    }
}
