import { ScrollView, VerticalBox, Button } from "std-widgets.slint";
export component NavWindow inherits Rectangle {
    in-out property <bool> open_curtain;

    height: 100%;
    background: #000000;
    width: open_curtain ? 15% : 0%;
    opacity: open_curtain ? 1 : 0;

    animate opacity {
        duration: 250ms;
        easing: ease-out;
    }

    animate width {
        duration: 250ms;
        easing: ease-in;
    }

    ScrollView {
        height: parent.height;
        width: parent.width;

        VerticalBox {
            alignment: start;
            spacing: 10px;

            Image {
                source: @image-url("icons/rocket.svg");
                width: 100px;
                height: 100px;
            }

            Text {
                text: "Menu";
                color: green;
                font-size: 32px;
            }
        }
    }
}
