import { ScrollView, VerticalBox, Button, HorizontalBox } from "std-widgets.slint";
import { AppConfig } from "./global.slint";

export component NavView inherits Rectangle {
    height: 100%;
    background: AppConfig.color_black;
    width: AppConfig.is_curtain_open ? 15% : 0%;
    opacity: AppConfig.is_curtain_open ? 1 : 0;

    animate opacity {
        duration: 500ms;
        easing: ease-out;
    }

    animate width {
        duration: 500ms;
        easing: ease-in-out-back;
    }

    ScrollView {
        property <length> height_offset: 2px;
        property <length> width_offset:  2px;
        padding: 2px;
        height: parent.height;
        width: parent.width;
        viewport-height: (AppConfig.tables.length * 100px) + 2px;
        viewport-width: parent.width;

        VerticalBox {
            alignment: start;
            spacing: 10px;

            HorizontalBox {
                alignment: center;
                width: 100%;

                Image {
                    source: @image-url("icons/sonic.svg");
                    width: 70px;
                    height: 70px;
                    touch := TouchArea {
                        mouse-cursor: pointer;
                        clicked => {
                            AppConfig.is-rocket-launched = !AppConfig.is-rocket-launched;
                        }
                    }
                }
            }

            HorizontalBox {
                alignment: center;
                width: 100%;

                Text {
                    text <=> AppConfig.db_name;
                    color: AppConfig.color_secondary;
                    font-size: 1.2rem;
                    letter-spacing: 1px;
                }
            }

            for t[i] in AppConfig.tables: HorizontalBox {
                width: 100%;
                spacing: 5px;

                Image {
                    source: @image-url("icons/db-doc.svg");
                    width: 30px;
                    height: 30px;
                }

                Text {
                    vertical-alignment: center;
                    text: t;
                    color: teal.brighter(70%);
                    font-weight: 700;
                    font-size: 1.2rem;
                    letter-spacing: 1px;
                    overflow: TextOverflow.elide;
                }
            }

            if (AppConfig.tables.length == 0): Text {
                text: "No tables found";
                color: crimson.brighter(30%);
                font-weight: 700;
                font-size: 1.1rem;
                letter-spacing: 1px;
                overflow: TextOverflow.elide;
                horizontal-alignment: center;
            }
        }
    }
}
