import { ScrollView, VerticalBox, Button } from "std-widgets.slint";
export component NavView inherits Rectangle {
    in-out property <bool> open_curtain;

    callback on-landing;

    height: 100%;
    background: #000000;
    width: open_curtain ? 15% : 0%;
    opacity: open_curtain ? 1 : 0;

    animate opacity {
        duration: 400ms;
        easing: ease-out;
    }

    animate width {
        duration: 400ms;
        easing: ease-in-out-back;
    }

    ScrollView {
        height: parent.height;
        width: parent.width;

        VerticalBox {
            alignment: start;
            spacing: 10px;

            Image {
                source: @image-url("icons/rocket.svg");
                width: 80px;
                height: 80px;

                touch := TouchArea {
                    mouse-cursor: pointer;
                    clicked => {
                        root.on-landing();
                    }
                }
            }

            Text {
                text: "Menu";
                color: green;
                font-size: 32px;
            }
        }
    }
}
