import { ScrollView, VerticalBox, Button, HorizontalBox } from "std-widgets.slint";
import { AppConfig } from "./global.slint";
export component NavView inherits Rectangle {
    height: 100%;
    background: #000000;
    width: AppConfig.is_curtain_open ? 15% : 0%;
    opacity: AppConfig.is_curtain_open ? 1 : 0;

    animate opacity {
        duration: 500ms;
        easing: ease-out;
    }

    animate width {
        duration: 500ms;
        easing: ease-in-out-back;
    }

    ScrollView {
        property <length> height_offset: 2px;
        property <length> width_offset:  4px;
        padding: 3px;
        height: parent.height;
        width: parent.width;
        viewport-height: (AppConfig.tables.length * 100px) + 2px;
        viewport-width: parent.width;

        VerticalBox {
            alignment: start;
            spacing: 10px;

            HorizontalBox {
                alignment: center;
                width: 100%;

                Image {
                    source: @image-url("icons/rocket.svg");
                    width: 70px;
                    height: 70px;
                    touch := TouchArea {
                        mouse-cursor: pointer;
                        clicked => {
                            AppConfig.is-rocket-launched = !AppConfig.is-rocket-launched;
                        }
                    }
                }
            }

            HorizontalBox {
                alignment: center;
                width: 100%;

                Text {
                    text <=> AppConfig.db_name;
                    color: greenyellow;
                    font-size: 1.3rem;
                    letter-spacing: 1px;
                }
            }

            for t[i] in AppConfig.tables: Text {
                text: t;
                color: teal;
                font-weight: 700;
                font-size: 1.1rem;
                letter-spacing: 1px;
            }

            if (AppConfig.tables.length == 0): Text {
                text: "No tables found";
                color: teal;
                font-weight: 700;
                font-size: 1.1rem;
                letter-spacing: 1px;
                wrap: TextWrap.word-wrap;
            }
        }
    }
}
