import { ScrollView, VerticalBox, Button } from "std-widgets.slint";
export component NavWindow inherits Rectangle {
    in property <bool> open_curtain: true;
    callback toggle-curtain;

    background: #333;
    width: open_curtain ? 15% : 0%;
    height: 100%;
    animate width {
        duration: 250ms;
        easing: ease-in;
    }

    ScrollView {
        height: parent.height;
        width: parent.width;

        VerticalBox {
            alignment: start;
            spacing: 10px;
            Button {
                width: 110px;
                height: 30px;
                text: "Toggle Curtain";
                primary: true;
                clicked => {
                    root.toggle_curtain();
                }
            }

            Text {
                text: "Menu";
                color: green;
                font-size: 32px;
            }
        }
    }
}
